# Setup

In [1]:
import pandas as pd
import numpy as np
import pickle
import time
from sklearn.preprocessing import StandardScaler
from copy import deepcopy

# ANN 
import tensorflow as tf
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Reshape
from tensorflow.keras import Input
from tensorflow.keras.initializers import Constant

from custom_methods import model_eval

datapath = '../Data/'

startTime = time.time()

tf.keras.__version__

'2.4.0'

## Import Data

In [2]:
filename = 'ann_ready.pickle'
infile = open(datapath+filename,'rb')
data = pickle.load(infile)
X = data['X']
Y = data['Y']
infile.close()

X.shape

(85217, 59, 17)

## Take subset of data

In [3]:
NUM_PEOPLE = 85217
NUM_TIMESTEPS = 59
NUM_VARS = X.shape[2]

X = X[:NUM_PEOPLE, -NUM_TIMESTEPS:, :]
Y = Y[:NUM_PEOPLE, :]

# Print info
print(f'Format: (num_data_objects, max_sequence_length, num_vars) = {X.shape}')
print(f'\nX: shape = {X.shape}')
print(X[1, :3, :5])
print(f'\nY: shape = {Y.shape}')
print(Y[1])

Format: (num_data_objects, max_sequence_length, num_vars) = (85217, 59, 17)

X: shape = (85217, 59, 17)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Y: shape = (85217, 2)
['10001-114314' False]


# Model

## Parameters

In [4]:
early_stopping = EarlyStopping(
    monitor='loss',
    min_delta=0.001,
    patience=2,
    restore_best_weights=True
)

model_params = {
    'OPTIMIZER':'adam', 
    'LOSS':'binary_crossentropy', 
    'METRICS':['binary_crossentropy'],
    #'CLASS_WEIGHT':class_weight,
    'BATCH_SIZE':500,
    'EPOCHS':1000,
    'CALLBACKS':[early_stopping],
    'VERBOSITY':0
}

## Model Structure

In [5]:
def make_model(x_shape, model_params, output_bias=None):
    if output_bias is not None:
        output_bias = Constant(output_bias)
        
    model = Sequential()

    model.add(Input(shape = (x_shape[1], x_shape[2])))

    # Reshape data
    model.add(Reshape(target_shape=(x_shape[2], x_shape[1],)))

    # Create 1st hidden layer
    model.add(Dense(units=1, activation='relu'))

    # Create reshape layer
    model.add(Reshape(target_shape=(X.shape[2],)))

    # Create 2nd Hidden Layer
    model.add(Dense(units=64, activation='relu'))

    # Create output layer
    model.add(Dense(units=1, activation='sigmoid', bias_initializer=output_bias))

    # Compile ANN
    model.compile(
        optimizer=model_params['OPTIMIZER'], 
        loss=model_params['LOSS'], 
        metrics=model_params['METRICS']
    )

    return model

In [6]:
make_model(x_shape=X.shape, model_params=model_params).summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
reshape (Reshape)            (None, 17, 59)            0         
_________________________________________________________________
dense (Dense)                (None, 17, 1)             60        
_________________________________________________________________
reshape_1 (Reshape)          (None, 17)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 64)                1152      
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 65        
Total params: 1,277
Trainable params: 1,277
Non-trainable params: 0
_________________________________________________________________


## K-Folds Method

In [7]:
def k_folds_ann(model_params:dict, x:np.ndarray, y:np.ndarray, num_folds:int, scale_axis:int, scaler):
    '''
    11/16/21
    Data Format: [num_data_objects, max_sequence_length, num_vars]
    Note: axis count begins at 0
    '''
    
    models = [None]*num_folds
    scalers = np.reshape([None]*num_folds*x.shape[2], (num_folds,x.shape[2]))
    class_weights = [None]*num_folds
    predictions = pd.DataFrame(columns=['ID', 'CMIS_MATCH', 'prediction'])
    
    shuffled_index = np.arange(x.shape[0])
    np.random.shuffle(shuffled_index)
    num_per_fold = int(np.round(len(shuffled_index)/num_folds))
    
    for fold in range(num_folds):
        
        # Find Data Splits
        if fold != num_folds - 1:
            fold_test_index = shuffled_index[fold*num_per_fold: (fold+1)*num_per_fold]
        else:
            fold_test_index = shuffled_index[fold*num_per_fold:]
        fold_train_index = [z for z in shuffled_index if z not in fold_test_index]
       
        x_train = x[fold_train_index].copy()
        y_train = y[fold_train_index].copy()
        x_test = x[fold_test_index].copy()
        y_test = y[fold_test_index].copy()
        
        # CLass Weight
        pos = int(y_train[:,1].sum())
        if pos == 0:
            pos = 1
        total = len(y_train)
        neg = total - pos

        weight_for_0 = (1 / neg) * (total / 2.0)
        weight_for_1 = (1 / pos) * (total / 2.0)
        class_weights[fold] = {0.0:weight_for_0, 1.0:weight_for_1}
        
        # Initial Output Bias
        output_bias = np.log([pos/neg])
        
        # Scaling
        for var in range(X.shape[2]):
            scalers[fold, var] = deepcopy(scaler)
            x_train[:, :, var] = scalers[fold, var].fit_transform(x_train[:, :, var])
            x_test[:, :, var] = scalers[fold, var].transform(x_test[:, :, var])
        
        # Create and Compile new Fold Model
        models[fold] = make_model(
            x_shape = x_train.shape,
            model_params = model_params,
            output_bias = output_bias
        )
        
        # Fit model
        models[fold].fit(
            x = tf.convert_to_tensor(x_train, np.float32),
            y = tf.convert_to_tensor(y_train[:,1], np.float32), 
            batch_size = model_params['BATCH_SIZE'], 
            epochs = model_params['EPOCHS'],
            class_weight = class_weights[fold],
            callbacks = model_params['CALLBACKS'],
            verbose = model_params['VERBOSITY'],
        )
        
        # Make Predictions for Fold
        fold_predictions = models[fold].predict(x=tf.convert_to_tensor(x_test, np.float32))
        try:
            fold_predictions = pd.concat(
                [
                    pd.Series(y_test[:,0], name='ID'), 
                    pd.Series(y_test[:,1], name='CMIS_MATCH'), 
                    pd.Series(np.transpose(fold_predictions)[0], name='prediction')
                ], 
                axis=1, 
                join='inner',
                ignore_index=False
            )
        except:
            print(fold_predictions[:2])
            return
        
        predictions = predictions.append(fold_predictions)
        
    # Aggregate things to return
    results = {'models':models, 'scalers':scalers, 'class_weights':class_weights, 'predictions':predictions}
    
    return results

# Run K-Folds

In [8]:
NUM_FOLDS = 4

results = k_folds_ann(
    model_params=model_params, 
    x=X, 
    y=Y, 
    num_folds=NUM_FOLDS, 
    scale_axis=2, 
    scaler=StandardScaler()
)

In [9]:
print(len(results['predictions']))
results['predictions'].head()

85217


ID CMIS_MATCH  prediction
0  203611-27568      False    0.486543
1  294114-66211      False    0.527877
2   30850-77594      False    0.408230
3    59958-5134      False    0.557167
4   198580-6434      False    0.395066

In [10]:
len(results['predictions']) / results['predictions']['ID'].nunique()

1.0

## Convert Predictions
* Output currently has prediction for each person-place combo
* Take maximum risk prediction for each person.  
* If person is labelled as both positive and negative, label them as positive.

In [11]:
predictions = results['predictions'].copy()
predictions['SPA_PER_ID'] = predictions['ID'].apply(lambda x: x.split('-')[0]).astype('int')

matches = predictions.groupby('SPA_PER_ID')['CMIS_MATCH'].any()
predictions = pd.concat([predictions.groupby('SPA_PER_ID')['prediction'].max(), matches], axis=1, join='inner', ignore_index=False)
predictions = predictions.reset_index()
del matches

print(len(predictions))
predictions.head()

84345


SPA_PER_ID  prediction  CMIS_MATCH
0           3    0.396382       False
1           4    0.475424       False
2           6    0.562406       False
3          12    0.347752       False
4          14    0.434371       False

# Time and Save

In [12]:
filename = 'ann_predictions.pickle'
outfile = open(datapath + filename, 'wb')
pickle.dump(predictions, outfile)
outfile.close()

In [13]:
from custom_methods.calc_time import calc_time_from_sec

calc_time_from_sec(time.time()-startTime)

hours:minutes:seconds = 0:1:1.7893447875976562
